apiVersion: v2
appVersion: v3.2.0
description: A Helm chart for customising the deployment of the Quarkus SRE Workshop.
name: quarkus-sre
version: 0.0.1
home: https://github.com/quarkus-sre/charts
maintainers:
  - name: gsampaio-rh
# dependencies:
#   - name: amqstreams
#     version: "0.0.1"
#     repository: https://github.com/quarkus-sre/charts
