{{- if .Values.enabled }}
{{- if .Values.grafana.datasource.prometheus }}
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
  namespace: {{ .Values.grafana_namespace }}
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      type: prometheus
      url: 'http://prometheus-operated:9090'
      version: 1
  name: prometheus-datasources.yaml
{{- end }}
{{- end }}