{{- if .Values.enabled }}
{{- if .Values.grafana.route }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: grf-route
  namespace: {{ .Values.grafana_namespace }}
spec:
  to:
    kind: Service
    name: grafana-service
  tls: null
  port:
    targetPort: grafana
{{- end }}
{{- end }}