{
 "title": "SRE Com Quarkus - Error Budget",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SLI Requests OK [1h]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(delta(CamelExchangesSucceeded_total[60m]))/sum(delta(CamelExchangesTotal_total[60m])))*100"
    }
   ]
  },
  {
   "title": "SLI UPS Response Time Higher than 500 ms [1h]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(delta(upsTimerRequest_seconds_bucket{camelContext=\"camel-1\",le=\"0.5\"}[60m])))/(sum(delta(CamelExchangesTotal_total{routeId=\"ups-out-route\"}[60m]))))*100 "
    }
   ]
  },
  {
   "title": "SLI Fedex Response Time Higher than 500 ms [1h]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(delta(fedexTimerRequest_seconds_bucket{camelContext=\"camel-1\",le=\"0.5\"}[60m])))/(sum(delta(CamelExchangesTotal_total{routeId=\"fedex-out-route\"}[60m]))))*100 "
    }
   ]
  },
  {
   "title": "SLO Label Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(upsTimerRequest_seconds_max_bucket[1h])) by (le))",
     "legendFormat": "UPS"
    }
   ]
  },
  {
   "title": "SLO Orders Diff",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Orders" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))"
    }
   ]
  },
  {
   "title": "SLO Requests [1h]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(CamelExchangesSucceeded_total[60m]))/sum(delta(CamelExchangesTotal_total[60m])))*100",
     "legendFormat": "SLI"
    }
   ]
  },
  {
   "title": "SLO Label Response Time Higher than 500 ms [1h]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum(delta(upsTimerRequest_seconds_bucket{camelContext=\"camel-1\",le=\"0.5\"}[60m])))/(sum(delta(CamelExchangesTotal_total{routeId=\"ups-out-route\"}[60m]))))*100 ",
     "legendFormat": "SLI UPS"
    },
    {
     "expr": "((sum(delta(fedexTimerRequest_seconds_bucket{camelContext=\"camel-1\",le=\"0.5\"}[60m])))/(sum(delta(CamelExchangesTotal_total{routeId=\"fedex-out-route\"}[60m]))))*100 ",
     "legendFormat": "SLI Fedex"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Orders Topic)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "SLO Kafka Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_producer_request_latency_avg{container=\"order-processor\"})"
    }
   ]
  },
  {
   "title": "SLO Label Latency P95",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(upsTimerRequest_seconds{camelContext=\"camel-1\",quantile=\"0.95\"})",
     "legendFormat": "UPS"
    },
    {
     "expr": "avg(fedexTimerRequest_seconds{camelContext=\"camel-1\",quantile=\"0.95\"})",
     "legendFormat": "Fedex"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Orders Topic)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Avg Time from Order Processor to Kafka",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_request_latency_avg{container=\"order-processor\"})",
     "legendFormat": "Order Processor"
    }
   ]
  },
  {
   "title": "Label Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(upsTimerRequest_seconds_max)",
     "legendFormat": "UPS"
    },
    {
     "expr": "avg(upsTimerRequest_seconds_max)",
     "legendFormat": "Fedex"
    }
   ]
  },
  {
   "title": "Fuse Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesTotal_total[60m]))"
    }
   ]
  },
  {
   "title": "SLO Requests [1h]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(CamelExchangesSucceeded_total[60m]))/sum(delta(CamelExchangesTotal_total[60m])))*100"
    }
   ]
  },
  {
   "title": "Fuse Requests Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesSucceeded_total[60m]))"
    }
   ]
  },
  {
   "title": "Fuse Requests Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesFailed_total[60m]))"
    }
   ]
  }
 ]
}