{
 "title": "SRE Com Quarkus - 2.0",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Orders Per App (1 Hour)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=\"orders\"}[1h]))",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"label-generator\"}[1h]))",
     "legendFormat": "Label Generator"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"inventory\"}[1h]))",
     "legendFormat": "Inventory"
    }
   ]
  },
  {
   "title": "Orders Shipped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "orders" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"})",
     "legendFormat": "Orders In"
    },
    {
     "expr": "min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))",
     "legendFormat": "Orders Shipped"
    }
   ]
  },
  {
   "title": "Orders Per App",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"})",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"label-generator\"})",
     "legendFormat": "Label Generator"
    },
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"inventory\"})",
     "legendFormat": "Inventory"
    },
    {
     "expr": "min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))",
     "legendFormat": "Orders Shipped"
    }
   ]
  },
  {
   "title": "SLO Orders Diff",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Orders Topic)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  }
 ]
}