{
 "title": "SRE Com Quarkus - Full",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Orders Per App (1 Hour)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=\"orders\"}[1h]))",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"label-generator\"}[1h]))",
     "legendFormat": "Label Generator"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"inventory\"}[1h]))",
     "legendFormat": "Inventory"
    }
   ]
  },
  {
   "title": "Avg Time from Order Processor to Kafka",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_request_latency_avg{container=\"order-processor\"})",
     "legendFormat": "Order Processor"
    }
   ]
  },
  {
   "title": "Orders Shipped per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "orders" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"})",
     "legendFormat": "Orders In"
    },
    {
     "expr": "min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))",
     "legendFormat": "Orders Shipped"
    }
   ]
  },
  {
   "title": "Order Processor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info_total{container=\"order-processor\"}"
    }
   ]
  },
  {
   "title": "Fuse Label",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info_total{container=\"label-generator\"}"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_info_total{container=\"inventory\"})"
    }
   ]
  },
  {
   "title": "Orders Consumed per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "Orders" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=\"orders\"}[1m])/60) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Orders Per App",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"})",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"label-generator\"})",
     "legendFormat": "Label Generator"
    },
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"inventory\"})",
     "legendFormat": "Inventory"
    },
    {
     "expr": "min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))",
     "legendFormat": "Orders Shipped"
    }
   ]
  },
  {
   "title": "HTTP Requests Errors Order Processor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "delta(http_server_requests_seconds_count{outcome=\"SERVER_ERROR\", container=\"order-processor\"}[60m])"
    }
   ]
  },
  {
   "title": "HTTP Errors Fuse Label",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(http_server_errors_total{container=\"label-generator\"}[60m]))"
    }
   ]
  },
  {
   "title": "HTTP Errors Inventory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(http_server_errors_total{container=\"inventory\"}[60m]))"
    }
   ]
  },
  {
   "title": "Label Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(upsTimerRequest_seconds_max)",
     "legendFormat": "UPS"
    },
    {
     "expr": "avg(fedexTimerRequest_seconds_max)",
     "legendFormat": "Fedex"
    }
   ]
  },
  {
   "title": "SLO Orders Diff",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))"
    }
   ]
  },
  {
   "title": "Kafka Errors Order Processor Last Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(kafka_producer_record_error_total{container=\"order-processor\"}[60m]))"
    }
   ]
  },
  {
   "title": "Fuse Exchange Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesFailed_total[60m]))"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Orders Topic)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Label Generator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(upsRequestCounter_total)", "legendFormat": "UPS" },
    { "expr": "sum(fedexRequestCounter_total)", "legendFormat": "Fedex" }
   ]
  },
  {
   "title": "HTTP Errors Last 15 Minutes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_server_errors_total{container=\"order-processor\"}[15m]))",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(delta(http_server_errors_total{container=\"label-generator\"}[15m]))",
     "legendFormat": "Fuse Label"
    },
    {
     "expr": "sum(delta(http_server_errors_total{container=\"inventory\"}[15m]))",
     "legendFormat": "Inventory"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Orders Topic)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Labels per Company",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(fedexRequestCounter_total)", "legendFormat": "Fedex" },
    { "expr": "sum(upsRequestCounter_total)", "legendFormat": "UPS" }
   ]
  },
  {
   "title": "Orders Per App (1 Hour)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=\"orders\"}[1h]))",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"label-generator\"}[1h]))",
     "legendFormat": "Label Generator"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"inventory\"}[1h]))",
     "legendFormat": "Inventory"
    }
   ]
  },
  {
   "title": "Kafka Consumers Offset",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Orders Shipped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "orders" }
   ],
   "targets": [
    {
     "expr": "min(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"})",
     "legendFormat": "Orders Shipped"
    }
   ]
  },
  {
   "title": "Orders Per App (Offset)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"orders\"}",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "kafka_consumergroup_current_offset{consumergroup=\"label-generator\"}",
     "legendFormat": "Label Generator"
    },
    {
     "expr": "kafka_consumergroup_current_offset{consumergroup=\"inventory\"}",
     "legendFormat": "Inventory"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 }, "options": { "content": "# 4 Golden Signals" } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_cpu_usage{container=\"order-processor\"})",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "avg(system_cpu_usage{container=\"fuse-label\"})",
     "legendFormat": "Fuse Label"
    },
    {
     "expr": "avg(system_cpu_usage{container=\"inventory\"})",
     "legendFormat": "Inventory"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Order Processor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(http_server_requests_seconds_sum{container=\"order-processor\",outcome=\"SUCCESS\"}/http_server_requests_seconds_count{container=\"order-processor\",outcome=\"SUCCESS\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{outcome=\"SUCCESS\"}) by (container)",
     "legendFormat": "SUCCESS {{container}}"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{outcome=\"SERVER_ERROR\"}) by (container)",
     "legendFormat": "ERROR {{container}}"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{container=\"order-processor\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Apps Health",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_info_total) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 89 }, "options": { "content": "# Refactor" } },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_errors_total{container=\"order-processor\"})",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(http_server_errors_total{container=\"fuse-label\"})",
     "legendFormat": "Fuse Label"
    },
    {
     "expr": "sum(http_server_errors_total{container=\"inventory\"})",
     "legendFormat": "Inventory"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_errors_total{container=\"order-processor\"})",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(http_server_errors_total{container=\"fuse-label\"})",
     "legendFormat": "Fuse Label"
    },
    {
     "expr": "sum(http_server_errors_total{container=\"inventory\"})",
     "legendFormat": "Inventory"
    }
   ]
  },
  {
   "title": "Orders Per App Last Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(application_sre_order_receiver_orders_total) - sum(application_sre_order_receiver_orders_total offset 60m)",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(sre_label_generator_orders_total) - sum(sre_label_generator_orders_total offset 60m)",
     "legendFormat": "Label Generator"
    },
    {
     "expr": "sum(sre_inventory_orders_total) - sum(sre_inventory_orders_total offset 60m)",
     "legendFormat": "Inventory"
    }
   ]
  },
  {
   "title": "Avg Time to Inventory (window 1 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(sre_inventory_total_time_seconds_sum) - sum(sre_inventory_total_time_seconds_sum offset 1m)) / (sum(sre_inventory_total_time_seconds_count) - sum(sre_inventory_total_time_seconds_count offset 1m))"
    }
   ]
  },
  {
   "title": "Avg Time to Label (window 1 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 109 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(sre_label_generator_total_time_seconds_sum) - sum(sre_label_generator_total_time_seconds_sum offset 1m)) / (sum(sre_label_generator_total_time_seconds_count) - sum(sre_label_generator_total_time_seconds_count offset 1m))"
    }
   ]
  },
  {
   "title": "Avg Time to Inv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sre_inventory_total_time_seconds_sum) / sum(sre_inventory_total_time_seconds_count)"
    }
   ]
  }
 ]
}