{
 "title": "SRE Com Quarkus - SLI, SLO, SLA 2.0",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SLA Orders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLI Orders Diff",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kafka_topic_partition_current_offset{topic=\"orders\"}) - (sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup)))) / (sum(kafka_topic_partition_current_offset{topic=\"orders\"}))*100"
      }
     ]
    },
    {
     "title": "Orders Diff",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Orders" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup)))"
      }
     ]
    },
    {
     "title": "SLA Orders Diff",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(kafka_topic_partition_current_offset{topic=\"orders\"}) - (sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup)))) / (sum(kafka_topic_partition_current_offset{topic=\"orders\"}))*100",
       "legendFormat": "SLI Orders Diff"
      }
     ]
    },
    {
     "title": "Consumer Group Lag (Orders Topic)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
       "legendFormat": "{{consumergroup}}"
      }
     ]
    },
    {
     "title": "Consumer Group Lag (Orders Topic)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
       "legendFormat": "{{consumergroup}}"
      }
     ]
    },
    {
     "title": "Fuse Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(CamelExchangesTotal_total[60m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Label Generator SLO Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Availability Target",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:objective:ratio{sloth_id=\"label-generator-label-providers-http-availability\"}*100"
    }
   ]
  },
  {
   "title": "Availability Target [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesTotal_total[60m]))*0.95"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:error_budget:ratio{sloth_id=\"label-generator-label-providers-http-availability\"}*100"
    }
   ]
  },
  {
   "title": "Error Budget [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesTotal_total[60m]))*0.05"
    }
   ]
  },
  {
   "title": "SLI Availability [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(delta(CamelExchangesSucceeded_total[1h]))/sum(delta(CamelExchangesTotal_total[1h])))*100"
    }
   ]
  },
  {
   "title": "Requests Success [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesSucceeded_total[60m]))"
    }
   ]
  },
  {
   "title": "Error Rate [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate1h{sloth_id=\"label-generator-label-providers-http-availability\"}*100"
    }
   ]
  },
  {
   "title": "Requests Errors [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesFailed_total[60m]))"
    }
   ]
  },
  {
   "title": "SLO Requests [1h]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(CamelExchangesSucceeded_total[60m]))/sum(delta(CamelExchangesTotal_total[60m])))*100",
     "legendFormat": "SLI Availability"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate1h{sloth_id=\"label-generator-label-providers-http-availability\"}*100",
     "legendFormat": "Error Rate 1h Availability"
    },
    {
     "expr": "slo:sli_error:ratio_rate5m{sloth_id=\"label-generator-label-providers-http-availability\"}*100",
     "legendFormat": "Error Rate 5m Availability"
    }
   ]
  },
  { "title": "Label Generator Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Availability Target",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:objective:ratio{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100"
    }
   ]
  },
  {
   "title": "Availability Target [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m]))*0.95"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:error_budget:ratio{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100"
    }
   ]
  },
  {
   "title": "Error Budget [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m]))*0.05"
    }
   ]
  },
  {
   "title": "SLI Fedex Latency 500 ms [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job) / sum(rate(fedexTimerRequest_seconds_count[60m])) by (job)"
    }
   ]
  },
  {
   "title": "Requests Success [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(delta(fedexTimerRequest_seconds_count[60m])) by (job)) - ((sum(delta(fedexTimerRequest_seconds_count[60m])) by (job)) - sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job) )"
    }
   ]
  },
  {
   "title": "SLI Fedex Latency 500 ms [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate1h{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100"
    }
   ]
  },
  {
   "title": "Requests Errors [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m])) - ignoring(le) sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m]))"
    }
   ]
  },
  {
   "title": "SLO Fedex Latency [1h]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job) / sum(delta(fedexTimerRequest_seconds_count[60m])) by (job))*100",
     "legendFormat": "SLI Fedex Latency"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate1h{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100",
     "legendFormat": "Error Rate 1h Fedex Latency"
    },
    {
     "expr": "slo:sli_error:ratio_rate5m{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100",
     "legendFormat": "Error Rate 5m Fedex Latency"
    }
   ]
  }
 ]
}