{
 "title": "SRE Com Quarkus - SLI, SLO, SLA - Final",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SLA Orders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLI Orders Diff",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kafka_topic_partition_current_offset{topic=\"orders\"}) - (sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup)))) / (sum(kafka_topic_partition_current_offset{topic=\"orders\"}))*100"
      }
     ]
    },
    {
     "title": "Orders Diff",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Orders" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup)))"
      }
     ]
    },
    {
     "title": "SLA Orders Diff",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(kafka_topic_partition_current_offset{topic=\"orders\"}) - (sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup)))) / (sum(kafka_topic_partition_current_offset{topic=\"orders\"}))*100",
       "legendFormat": "SLI Orders Diff"
      }
     ]
    },
    {
     "title": "Consumer Group Lag (Orders Topic)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
       "legendFormat": "{{consumergroup}}"
      }
     ]
    },
    {
     "title": "Consumer Group Lag (Orders Topic)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
       "legendFormat": "{{consumergroup}}"
      }
     ]
    },
    {
     "title": "Fuse Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(CamelExchangesTotal_total[60m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Label Generator SLO Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Availability Target",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:objective:ratio{sloth_id=\"label-generator-label-providers-http-availability\"}*100"
    }
   ]
  },
  {
   "title": "Availability Target [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesTotal_total[60m]))*0.95"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:error_budget:ratio{sloth_id=\"label-generator-label-providers-http-availability\"}*100"
    }
   ]
  },
  {
   "title": "Error Budget [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesTotal_total[60m]))*0.05"
    }
   ]
  },
  {
   "title": "Over Error Budget 1h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(delta(CamelExchangesFailed_total[60m])) - sum(delta(CamelExchangesTotal_total[60m]))*0.05)*100)/(sum(delta(CamelExchangesTotal_total[60m]))*0.05)"
    }
   ]
  },
  {
   "title": "Over Error Budget [1h]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum(delta(CamelExchangesFailed_total[60m])) - sum(delta(CamelExchangesTotal_total[60m]))*0.05)*100)/(sum(delta(CamelExchangesTotal_total[60m]))*0.05)",
     "legendFormat": "Over Error Budget 1h Availability"
    },
    {
     "expr": "((sum(delta(CamelExchangesFailed_total[5m])) - sum(delta(CamelExchangesTotal_total[5m]))*0.05)*100)/(sum(delta(CamelExchangesTotal_total[5m]))*0.05)",
     "legendFormat": "Over Error Budget 5m Availability"
    }
   ]
  },
  {
   "title": "SLI Availability [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(delta(CamelExchangesSucceeded_total[1h]))/sum(delta(CamelExchangesTotal_total[1h])))*100"
    }
   ]
  },
  {
   "title": "Requests Success [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesSucceeded_total[60m]))"
    }
   ]
  },
  {
   "title": "Error Rate [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate1h{sloth_id=\"label-generator-label-providers-http-availability\"}*100"
    }
   ]
  },
  {
   "title": "Requests Errors [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesFailed_total[60m]))"
    }
   ]
  },
  {
   "title": "Burn Rate 1h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:burn_rate1h:ratio{sloth_id=\"label-generator-label-providers-http-availability\"}"
    }
   ]
  },
  {
   "title": "Burn Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "slo:burn_rate1h:ratio{sloth_id=\"label-generator-label-providers-http-availability\"}",
     "legendFormat": "Burn Rate 1h Availability"
    },
    {
     "expr": "slo:current_burn_rate:ratio{sloth_id=\"label-generator-label-providers-http-availability\"}",
     "legendFormat": "Burn Rate 5m Availability"
    }
   ]
  },
  {
   "title": "SLO Requests [1h]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(CamelExchangesSucceeded_total[60m]))/sum(delta(CamelExchangesTotal_total[60m])))*100",
     "legendFormat": "SLI Availability"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate1h{sloth_id=\"label-generator-label-providers-http-availability\"}*100",
     "legendFormat": "Error Rate 1h Availability"
    },
    {
     "expr": "slo:sli_error:ratio_rate5m{sloth_id=\"label-generator-label-providers-http-availability\"}*100",
     "legendFormat": "Error Rate 5m Availability"
    }
   ]
  },
  {
   "title": "Error Rate [5m]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate5m{sloth_id=\"label-generator-label-providers-http-availability\"}*100"
    }
   ]
  },
  {
   "title": "Burn Rate 5m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_id=\"label-generator-label-providers-http-availability\"}"
    }
   ]
  },
  {
   "title": "SLO Target",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesTotal_total[60m]))",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum(delta(CamelExchangesTotal_total[60m]))*0.95",
     "legendFormat": "Target"
    },
    {
     "expr": "sum(delta(CamelExchangesTotal_total[60m]))*0.95 - sum(delta(CamelExchangesTotal_total[60m]))",
     "legendFormat": "Diff"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(CamelExchangesTotal_total[60m]))*0.05",
     "legendFormat": "Budget"
    },
    {
     "expr": "sum(delta(CamelExchangesFailed_total[60m]))",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum(delta(CamelExchangesFailed_total[60m])) - sum(delta(CamelExchangesTotal_total[60m]))*0.05",
     "legendFormat": "Diff"
    }
   ]
  },
  { "title": "Label Generator Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Availability Target",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:objective:ratio{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100"
    }
   ]
  },
  {
   "title": "Availability Target [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m]))*0.95"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:error_budget:ratio{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100"
    }
   ]
  },
  {
   "title": "Error Budget [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m]))*0.05"
    }
   ]
  },
  {
   "title": "Over Error Budget 1h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(delta(fedexTimerRequest_seconds_count[60m])) by (job) - sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job)) - ((sum(delta(fedexTimerRequest_seconds_count[60m])) by (job))*0.05))  / (sum(delta(fedexTimerRequest_seconds_count[60m])) by (job)*0.05))*100"
    }
   ]
  },
  {
   "title": "Over Error Budget [1h]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((sum(delta(fedexTimerRequest_seconds_count[60m])) by (job) - sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job)) - ((sum(delta(fedexTimerRequest_seconds_count[60m])) by (job))*0.05))  / (sum(delta(fedexTimerRequest_seconds_count[60m])) by (job)*0.05))*100",
     "legendFormat": "Over Error Budget 1h Latency"
    },
    {
     "expr": "(((sum(delta(fedexTimerRequest_seconds_count[5m])) by (job) - sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[5m])) by (job)) - ((sum(delta(fedexTimerRequest_seconds_count[5m])) by (job))*0.05))  / (sum(delta(fedexTimerRequest_seconds_count[5m])) by (job)*0.05))*100",
     "legendFormat": "Over Error Budget 5m Latency"
    }
   ]
  },
  {
   "title": "SLI Fedex Latency 500 ms [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job) / sum(rate(fedexTimerRequest_seconds_count[60m])) by (job)"
    }
   ]
  },
  {
   "title": "Requests Success [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(delta(fedexTimerRequest_seconds_count[60m])) by (job)) - ((sum(delta(fedexTimerRequest_seconds_count[60m])) by (job)) - sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job) )"
    }
   ]
  },
  {
   "title": "SLI Fedex Latency 500 ms [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate1h{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100"
    }
   ]
  },
  {
   "title": "Requests Errors [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m])) - ignoring(le) sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m]))"
    }
   ]
  },
  {
   "title": "Burn Rate 1h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:burn_rate1h:ratio{sloth_id=\"label-generator-shipping-label-fedex-latency\"}"
    }
   ]
  },
  {
   "title": "Burn Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "slo:burn_rate1h:ratio{sloth_id=\"label-generator-shipping-label-fedex-latency\"}",
     "legendFormat": "Burn Rate 1h Latency"
    },
    {
     "expr": "slo:current_burn_rate:ratio{sloth_id=\"label-generator-shipping-label-fedex-latency\"}",
     "legendFormat": "Burn Rate 5m Latency"
    }
   ]
  },
  {
   "title": "SLO Fedex Latency [1h]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job) / sum(delta(fedexTimerRequest_seconds_count[60m])) by (job))*100",
     "legendFormat": "SLI Fedex Latency"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate1h{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100",
     "legendFormat": "Error Rate 1h Fedex Latency"
    },
    {
     "expr": "slo:sli_error:ratio_rate5m{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100",
     "legendFormat": "Error Rate 5m Fedex Latency"
    }
   ]
  },
  {
   "title": "Error Rate [5m]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate5m{sloth_id=\"label-generator-shipping-label-fedex-latency\"}*100"
    }
   ]
  },
  {
   "title": "Burn Rate 5m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_id=\"label-generator-shipping-label-fedex-latency\"}"
    }
   ]
  },
  {
   "title": "SLO Target",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m]))",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m]))*0.95",
     "legendFormat": "Target"
    },
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m]))*0.95 - sum(delta(fedexTimerRequest_seconds_count[60m]))",
     "legendFormat": "Diff"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m]))*0.05",
     "legendFormat": "Budget"
    },
    {
     "expr": "sum(delta(fedexTimerRequest_seconds_count[60m])) by (job) - sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job) ",
     "legendFormat": "Actual"
    },
    {
     "expr": "(sum(delta(fedexTimerRequest_seconds_count[60m])) by (job) - sum(delta(fedexTimerRequest_seconds_bucket{le=\"0.5\"}[60m])) by (job) ) - (sum(delta(fedexTimerRequest_seconds_count[60m])) by (job)*0.05)",
     "legendFormat": "Diff"
    },
    {}
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLI UPS Response Time Higher than 500 ms [1h]",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum(delta(upsTimerRequest_seconds_bucket{camelContext=\"camel-1\",le=\"0.5\"}[60m])))/(sum(delta(CamelExchangesTotal_total{routeId=\"ups-out-route\"}[60m]))))*100 "
      }
     ]
    },
    {
     "title": "Fedex Under 500",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(fedexTimerRequest_seconds_bucket{camelContext=\"camel-1\",le=\"0.5\"}[60m]))"
      }
     ]
    },
    {
     "title": "SLI Fedex Response Time Higher than 500 ms [1h]",
     "type": "stat",
     "gridPos": { "h": 12, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(delta(CamelExchangesTotal_total{routeId=\"fedex-out-route\"}[60m]))) - (sum(delta(fedexTimerRequest_seconds_bucket{camelContext=\"camel-1\",le=\"0.5\"}[60m])))"
      }
     ]
    },
    {
     "title": "SLO Label Latency P95",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(upsTimerRequest_seconds{camelContext=\"camel-1\",quantile=\"0.95\"})",
       "legendFormat": "UPS"
      },
      {
       "expr": "avg(fedexTimerRequest_seconds{camelContext=\"camel-1\",quantile=\"0.95\"})",
       "legendFormat": "Fedex"
      }
     ]
    },
    {
     "title": "Fedex Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(CamelExchangesTotal_total{routeId=\"fedex-out-route\"}[60m]))"
      }
     ]
    },
    {
     "title": "SLO Label Response Time Higher than 500 ms [1h]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((sum(delta(upsTimerRequest_seconds_bucket{camelContext=\"camel-1\",le=\"0.5\"}[60m])))/(sum(delta(CamelExchangesTotal_total{routeId=\"ups-out-route\"}[60m]))))*100 ",
       "legendFormat": "SLI UPS"
      },
      {
       "expr": "((sum(delta(fedexTimerRequest_seconds_bucket{camelContext=\"camel-1\",le=\"0.5\"}[60m])))/(sum(delta(CamelExchangesTotal_total{routeId=\"fedex-out-route\"}[60m]))))*100 ",
       "legendFormat": "SLI Fedex"
      }
     ]
    },
    {
     "title": "Label Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(upsTimerRequest_seconds_max)",
       "legendFormat": "UPS"
      },
      {
       "expr": "avg(fedexTimerRequest_seconds_max)",
       "legendFormat": "Fedex"
      }
     ]
    }
   ]
  }
 ]
}