{
 "title": "SRE Com Quarkus - 3.0",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Orders Per App (1 Hour)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=\"orders\"}[1h]))",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"label-generator\"}[1h]))",
     "legendFormat": "Label Generator"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"inventory\"}[1h]))",
     "legendFormat": "Inventory"
    }
   ]
  },
  {
   "title": "Avg Time from Order Processor to Kafka",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_request_latency_avg{container=\"order-processor\"})",
     "legendFormat": "Order Processor"
    }
   ]
  },
  {
   "title": "Orders Shipped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "orders" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"})",
     "legendFormat": "Orders In"
    },
    {
     "expr": "min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))",
     "legendFormat": "Orders Shipped"
    }
   ]
  },
  {
   "title": "Order Processor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info_total{container=\"order-processor\"}"
    }
   ]
  },
  {
   "title": "Fuse Label",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info_total{container=\"label-generator\"}"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_info_total{container=\"inventory\"})"
    }
   ]
  },
  {
   "title": "Orders Consumed per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "Orders" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=\"orders\"}[1m])/60) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Orders Per App",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"})",
     "legendFormat": "Order Processor"
    },
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"label-generator\"})",
     "legendFormat": "Label Generator"
    },
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"inventory\"})",
     "legendFormat": "Inventory"
    },
    {
     "expr": "min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))",
     "legendFormat": "Orders Shipped"
    }
   ]
  },
  {
   "title": "Label Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(upsTimerRequest_seconds_max)",
     "legendFormat": "UPS"
    },
    {
     "expr": "avg(fedexTimerRequest_seconds_max)",
     "legendFormat": "Fedex"
    }
   ]
  },
  {
   "title": "SLO Orders Diff",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"orders\"}) -  min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Orders Topic)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Label Generator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(upsRequestCounter_total)", "legendFormat": "UPS" },
    { "expr": "sum(fedexRequestCounter_total)", "legendFormat": "Fedex" }
   ]
  },
  {
   "title": "Consumer Group Lag (Orders Topic)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Labels per Company",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(fedexRequestCounter_total)", "legendFormat": "Fedex" },
    { "expr": "sum(upsRequestCounter_total)", "legendFormat": "UPS" }
   ]
  },
  {
   "title": "Kafka Consumers Offset",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{topic=\"orders\"}) by (consumergroup)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Orders Shipped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "orders" }
   ],
   "targets": [
    {
     "expr": "min(sum(kafka_consumergroup_current_offset{consumergroup=~\"inventory|label-generator\"}) by (consumergroup))",
     "legendFormat": "Orders Shipped"
    }
   ]
  }
 ]
}