---
enabled: true
pipeline_namespace: quarkus-ci-cd

nexus:
  name: nexus
  image: docker.io/sonatype/nexus3
  route: true
  maven: true

tekton:
  name: tekton
  storage:
    accessmode: ReadWriteOnce
    volumemode: Filesystem
    requests:
      storage: 1Gi
  task:
    buildah:
      name: buildah
    maven:
      name: maven
    kn:
      name: kn
  