---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: prometheus
  name: prometheus-rules-label-fedex-latency-slos
  namespace: kafka-logging
spec:
  groups:
  - name: sloth-slo-sli-recordings-label-generator-shipping-label-fedex-latency
    rules:
    - record: slo:sli_error:ratio_rate5m
      expr: |
        ((
          sum(rate(fedexTimerRequest_seconds_count[5m])) by (job)
          -
          sum(rate(fedexTimerRequest_seconds_bucket{le="0.5"}[5m])) by (job)
        )
        )
        /
        (sum(rate(fedexTimerRequest_seconds_count[5m])) by (job))
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
        sloth_window: 5m
    - record: slo:sli_error:ratio_rate30m
      expr: |
        ((
          sum(rate(fedexTimerRequest_seconds_count[30m])) by (job)
          -
          sum(rate(fedexTimerRequest_seconds_bucket{le="0.5"}[30m])) by (job)
        )
        )
        /
        (sum(rate(fedexTimerRequest_seconds_count[30m])) by (job))
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
        sloth_window: 30m
    - record: slo:sli_error:ratio_rate1h
      expr: |
        ((
          sum(rate(fedexTimerRequest_seconds_count[1h])) by (job)
          -
          sum(rate(fedexTimerRequest_seconds_bucket{le="0.5"}[1h])) by (job)
        )
        )
        /
        (sum(rate(fedexTimerRequest_seconds_count[1h])) by (job))
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
        sloth_window: 1h
    - record: slo:sli_error:ratio_rate2h
      expr: |
        ((
          sum(rate(fedexTimerRequest_seconds_count[2h])) by (job)
          -
          sum(rate(fedexTimerRequest_seconds_bucket{le="0.5"}[2h])) by (job)
        )
        )
        /
        (sum(rate(fedexTimerRequest_seconds_count[2h])) by (job))
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
        sloth_window: 2h
    - record: slo:sli_error:ratio_rate6h
      expr: |
        ((
          sum(rate(fedexTimerRequest_seconds_count[6h])) by (job)
          -
          sum(rate(fedexTimerRequest_seconds_bucket{le="0.5"}[6h])) by (job)
        )
        )
        /
        (sum(rate(fedexTimerRequest_seconds_count[6h])) by (job))
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
        sloth_window: 6h
    - record: slo:sli_error:ratio_rate1d
      expr: |
        ((
          sum(rate(fedexTimerRequest_seconds_count[1d])) by (job)
          -
          sum(rate(fedexTimerRequest_seconds_bucket{le="0.5"}[1d])) by (job)
        )
        )
        /
        (sum(rate(fedexTimerRequest_seconds_count[1d])) by (job))
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
        sloth_window: 1d
    - record: slo:sli_error:ratio_rate3d
      expr: |
        ((
          sum(rate(fedexTimerRequest_seconds_count[3d])) by (job)
          -
          sum(rate(fedexTimerRequest_seconds_bucket{le="0.5"}[3d])) by (job)
        )
        )
        /
        (sum(rate(fedexTimerRequest_seconds_count[3d])) by (job))
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
        sloth_window: 3d
    - record: slo:sli_error:ratio_rate30d
      expr: |
        sum_over_time(slo:sli_error:ratio_rate5m{sloth_id="label-generator-shipping-label-fedex-latency", sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}[30d])
        / ignoring (sloth_window)
        count_over_time(slo:sli_error:ratio_rate5m{sloth_id="label-generator-shipping-label-fedex-latency", sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}[30d])
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
        sloth_window: 30d
  - name: sloth-slo-meta-recordings-label-generator-shipping-label-fedex-latency
    rules:
    - record: slo:objective:ratio
      expr: vector(0.95)
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
    - record: slo:error_budget:ratio
      expr: vector(1-0.95)
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
    - record: slo:time_period:days
      expr: vector(30)
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
    - record: slo:current_burn_rate:ratio
      expr: |
        slo:sli_error:ratio_rate5m{sloth_id="label-generator-shipping-label-fedex-latency", sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}
        / on(sloth_id, sloth_slo, sloth_service) group_left
        slo:error_budget:ratio{sloth_id="label-generator-shipping-label-fedex-latency", sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
    - record: slo:current_error_budget_remaining:ratio
      expr: 1 - slo:current_burn_rate:ratio{sloth_id="label-generator-shipping-label-fedex-latency",
        sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
    - record: slo:burn_rate1h:ratio
      expr: |
        slo:sli_error:ratio_rate1h{sloth_id="label-generator-shipping-label-fedex-latency", sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}
        / on(sloth_id, sloth_slo, sloth_service) group_left
        slo:error_budget:ratio{sloth_id="label-generator-shipping-label-fedex-latency", sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
    - record: slo:error_budget_remaining1h:ratio
      expr: 1 - slo:burn_rate1h:ratio{sloth_id="label-generator-shipping-label-fedex-latency",
        sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
    - record: slo:period_burn_rate:ratio
      expr: |
        slo:sli_error:ratio_rate30d{sloth_id="label-generator-shipping-label-fedex-latency", sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}
        / on(sloth_id, sloth_slo, sloth_service) group_left
        slo:error_budget:ratio{sloth_id="label-generator-shipping-label-fedex-latency", sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
    - record: slo:period_error_budget_remaining:ratio
      expr: 1 - slo:period_burn_rate:ratio{sloth_id="label-generator-shipping-label-fedex-latency",
        sloth_service="label-generator", sloth_slo="shipping-label-fedex-latency"}
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
    - record: sloth_slo_info
      expr: vector(1)
      labels:
        category: latency
        owner: redhat-sre
        sloth_id: label-generator-shipping-label-fedex-latency
        sloth_mode: cli-gen-prom
        sloth_objective: "95"
        sloth_service: label-generator
        sloth_slo: shipping-label-fedex-latency
        sloth_spec: prometheus/v1
        sloth_version: sloth-helm-chart-0.5.2-20-g481c16f
