{{- if .Values.enabled }}
{{- if .Values.keda }}
---
apiVersion: keda.sh/v1alpha1
kind: KedaController
metadata:
  name: {{ .Values.keda.name }}
  namespace: {{ .Values.keda_namespace }}
spec:
  operator:
    logLevel: {{ .Values.keda.loglelevel }}
    logEncoder: {{ .Values.keda.logencoder }}
  metricsServer:
    logLevel: '0'
  serviceAccount: {}
  watchNamespace: ''
{{- end }}
{{- end }}
