apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: inventory-scaled-object
  namespace: quarkus-dev
  labels:
    deploymentName: inventory
spec:
  scaleTargetRef:
    name: inventory
  pollingInterval: 5 #Interval for polling
  cooldownPeriod: 10
  minReplicaCount: 1   #Optional Default 0
  maxReplicaCount: 3 #Optional Default 100
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-hub-cluster-kafka-bootstrap.kafka-streaming.svc.cluster.local:9092
        consumerGroup: inventory
        topic: orders
        # Optional
        lagThreshold: "10"
        offsetResetPolicy: latest