apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: label-generator-scaled-object
  namespace: quarkus-dev
  labels:
    deploymentName: label-generator
spec:
  scaleTargetRef:
    name: label-generator
  pollingInterval: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-hub-cluster-kafka-bootstrap.kafka-streaming.svc.cluster.local:9092
        consumerGroup: label-generator
        topic: orders
        # Optional
        lagThreshold: "10"
        offsetResetPolicy: latest