---
enabled: true
kafka_namespace: kafka-streaming

# operator:
#   name: amq-streams
#   namespace: openshift-operators
#   channel: stable
#   version: amqstreams.v1.6.3

metrics:
  configmap:
    name: kafka-metrics
    kafka:
      key: kafka-metrics-config.yml
    zookeeper:
      key: zookeeper-metrics-config.yml

kafka:
  name: kafka-hub-cluster
  # labels:
  #   app: kafka-hub
  version: 3.4.0
  replicas: 3
  storage:
    type: persistent-claim
    size: 10Gi
  kafkaexporter: true

zookeeper:
  replicas: 3
  storage:
    type: persistent-claim
    size: 10Gi

