{{- if .Values.enabled }}
{{- if .Values.jaeger }}
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: {{ .Values.jaeger.name }}
  namespace: {{ .Values.jaeger_namespace }}
spec:
  allInOne:
    options:
      log-level: {{ .Values.jaeger.loglelevel }}
  strategy: {{ .Values.jaeger.strategy }}
{{- end }}
{{- end }}
