{{- if .Values.enabled }}
{{- if .Values.nexus.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.nexus.name }}-route
  namespace: {{ .Values.pipeline_namespace }}
spec:
  host: 
  to:
    kind: Service
    name: {{ .Values.nexus.name }}
  port:
    targetPort: 8081-tcp
  wildcardPolicy: None
{{- end }}
{{- end }}
