{{- if .Values.enabled }}
{{- if .Values.nexus }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nexus.name }}
  namespace: {{ .Values.pipeline_namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.nexus.name }}
  ports:
    - port: 8081
      targetPort: 8081-tcp
{{- end }}
{{- end }}
