apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: '2022-05-23T19:52:30Z'
  generation: 1
  labels:
    operators.coreos.com/amq-streams.openshift-operators: ''
  managedFields:
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:channel': {}
          'f:installPlanApproval': {}
          'f:name': {}
          'f:source': {}
          'f:sourceNamespace': {}
          'f:startingCSV': {}
      manager: Mozilla
      operation: Update
      time: '2022-05-23T19:52:30Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:operators.coreos.com/amq-streams.openshift-operators': {}
      manager: olm
      operation: Update
      time: '2022-05-23T19:52:30Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:installedCSV': {}
          'f:currentCSV': {}
          'f:catalogHealth': {}
          'f:installPlanRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
          'f:installPlanGeneration': {}
          'f:conditions': {}
          .: {}
          'f:installplan':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:uuid': {}
          'f:lastUpdated': {}
          'f:state': {}
      manager: catalog
      operation: Update
      subresource: status
      time: '2022-05-23T19:52:59Z'
  name: amq-streams
  namespace: openshift-operators
  resourceVersion: '55682'
  uid: 2c5bcfcf-490a-42ce-b511-1b3d481ad634
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v2.1.0-4
status:
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-klrjw
    uuid: 295262c2-e0a9-4a26-949c-78589679464c
  lastUpdated: '2022-05-23T20:18:19Z'
  installedCSV: amqstreams.v2.1.0-4
  currentCSV: amqstreams.v2.1.0-4
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-klrjw
    namespace: openshift-operators
    resourceVersion: '34062'
    uid: 295262c2-e0a9-4a26-949c-78589679464c
  state: AtLatestKnown
  catalogHealth:
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: certified-operators
        namespace: openshift-marketplace
        resourceVersion: '33738'
        uid: 29e414c1-1132-454b-9b0c-607547422fb6
      healthy: true
      lastUpdated: '2022-05-23T19:52:31Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: community-operators
        namespace: openshift-marketplace
        resourceVersion: '32926'
        uid: 6e6c9b26-8b75-4921-b922-d96f1d3f68e1
      healthy: true
      lastUpdated: '2022-05-23T19:52:31Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-marketplace
        namespace: openshift-marketplace
        resourceVersion: '29322'
        uid: 3dced85d-65c1-449f-ba25-8b2fcaa9faa0
      healthy: true
      lastUpdated: '2022-05-23T19:52:31Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-operators
        namespace: openshift-marketplace
        resourceVersion: '33735'
        uid: d766e537-90bf-42fb-89d0-04121f925f69
      healthy: true
      lastUpdated: '2022-05-23T19:52:31Z'
  conditions:
    - lastTransitionTime: '2022-05-23T19:52:31Z'
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      status: 'False'
      type: CatalogSourcesUnhealthy
    - status: 'False'
      type: ResolutionFailed
  installPlanGeneration: 1
