apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: '2022-05-23T19:56:16Z'
  generation: 1
  labels:
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ''
  managedFields:
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:channel': {}
          'f:installPlanApproval': {}
          'f:name': {}
          'f:source': {}
          'f:sourceNamespace': {}
          'f:startingCSV': {}
      manager: Mozilla
      operation: Update
      time: '2022-05-23T19:56:16Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators': {}
      manager: olm
      operation: Update
      time: '2022-05-23T19:56:16Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:installedCSV': {}
          'f:currentCSV': {}
          'f:catalogHealth': {}
          'f:installPlanRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
          'f:installPlanGeneration': {}
          'f:conditions': {}
          .: {}
          'f:installplan':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:uuid': {}
          'f:lastUpdated': {}
          'f:state': {}
      manager: catalog
      operation: Update
      subresource: status
      time: '2022-05-23T19:56:28Z'
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
  resourceVersion: '50305'
  uid: 0cb0c52c-5be6-47da-b0a5-e192886d8510
spec:
  channel: pipelines-1.7
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-pipelines-operator-rh.v1.7.0
status:
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-hf9hx
    uuid: e1a3639f-d25c-4e39-a5b0-dd4052d302a6
  lastUpdated: '2022-05-23T20:11:36Z'
  installedCSV: openshift-pipelines-operator-rh.v1.7.0
  currentCSV: openshift-pipelines-operator-rh.v1.7.0
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-hf9hx
    namespace: openshift-operators
    resourceVersion: '36356'
    uid: e1a3639f-d25c-4e39-a5b0-dd4052d302a6
  state: AtLatestKnown
  catalogHealth:
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: certified-operators
        namespace: openshift-marketplace
        resourceVersion: '33738'
        uid: 29e414c1-1132-454b-9b0c-607547422fb6
      healthy: true
      lastUpdated: '2022-05-23T19:56:16Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: community-operators
        namespace: openshift-marketplace
        resourceVersion: '32926'
        uid: 6e6c9b26-8b75-4921-b922-d96f1d3f68e1
      healthy: true
      lastUpdated: '2022-05-23T19:56:16Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-marketplace
        namespace: openshift-marketplace
        resourceVersion: '35981'
        uid: 3dced85d-65c1-449f-ba25-8b2fcaa9faa0
      healthy: true
      lastUpdated: '2022-05-23T19:56:16Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-operators
        namespace: openshift-marketplace
        resourceVersion: '33735'
        uid: d766e537-90bf-42fb-89d0-04121f925f69
      healthy: true
      lastUpdated: '2022-05-23T19:56:16Z'
  conditions:
    - lastTransitionTime: '2022-05-23T19:56:16Z'
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      status: 'False'
      type: CatalogSourcesUnhealthy
    - status: 'False'
      type: ResolutionFailed
  installPlanGeneration: 2
