apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: '2022-05-23T19:55:17Z'
  generation: 1
  labels:
    operators.coreos.com/jaeger-product.openshift-distributed-tracing: ''
  managedFields:
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:channel': {}
          'f:installPlanApproval': {}
          'f:name': {}
          'f:source': {}
          'f:sourceNamespace': {}
          'f:startingCSV': {}
      manager: Mozilla
      operation: Update
      time: '2022-05-23T19:55:17Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:operators.coreos.com/jaeger-product.openshift-distributed-tracing': {}
      manager: olm
      operation: Update
      time: '2022-05-23T19:55:17Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:installedCSV': {}
          'f:currentCSV': {}
          'f:catalogHealth': {}
          'f:installPlanRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
          'f:installPlanGeneration': {}
          'f:conditions': {}
          .: {}
          'f:installplan':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:uuid': {}
          'f:lastUpdated': {}
          'f:state': {}
      manager: catalog
      operation: Update
      subresource: status
      time: '2022-05-23T19:55:31Z'
  name: jaeger-product
  namespace: openshift-distributed-tracing
  resourceVersion: '50208'
  uid: e92de432-8bf5-4925-9975-17cff31d681c
spec:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: jaeger-operator.v1.30.2
status:
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-l2c7h
    uuid: 7e1e57bc-36e0-44f5-a443-b6d768ffe0c2
  lastUpdated: '2022-05-23T20:11:28Z'
  installedCSV: jaeger-operator.v1.30.2
  currentCSV: jaeger-operator.v1.30.2
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-l2c7h
    namespace: openshift-distributed-tracing
    resourceVersion: '35517'
    uid: 7e1e57bc-36e0-44f5-a443-b6d768ffe0c2
  state: AtLatestKnown
  catalogHealth:
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: certified-operators
        namespace: openshift-marketplace
        resourceVersion: '33738'
        uid: 29e414c1-1132-454b-9b0c-607547422fb6
      healthy: true
      lastUpdated: '2022-05-23T19:55:18Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: community-operators
        namespace: openshift-marketplace
        resourceVersion: '32926'
        uid: 6e6c9b26-8b75-4921-b922-d96f1d3f68e1
      healthy: true
      lastUpdated: '2022-05-23T19:55:18Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-marketplace
        namespace: openshift-marketplace
        resourceVersion: '29322'
        uid: 3dced85d-65c1-449f-ba25-8b2fcaa9faa0
      healthy: true
      lastUpdated: '2022-05-23T19:55:18Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-operators
        namespace: openshift-marketplace
        resourceVersion: '33735'
        uid: d766e537-90bf-42fb-89d0-04121f925f69
      healthy: true
      lastUpdated: '2022-05-23T19:55:18Z'
  conditions:
    - lastTransitionTime: '2022-05-23T19:55:18Z'
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      status: 'False'
      type: CatalogSourcesUnhealthy
    - status: 'False'
      type: ResolutionFailed
  installPlanGeneration: 1
